# Nome da sua aplicação
spring.application.name=cycloflow

# Conexão com o SQL Server (banco cycloflow_db)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cycloflow_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=karinaluis22
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Dialeto do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Exibir os comandos SQL no console
spring.jpa.show-sql=true

# Desativa a criação automática de tabelas pelo Spring
spring.jpa.hibernate.ddl-auto=none